# Generated by Django 6.0 on 2026-02-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'brand')},
        ),
    ]
