# Generated by Django 6.0.1 on 2026-01-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short intro for customers', max_length=300),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='job_title',
            field=models.CharField(default='Stylist', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='expertise',
            field=models.CharField(default='General', help_text='Comma separated skills', max_length=255),
        ),
    ]
