# Generated by Django 6.0 on 2026-02-02 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile_bio_employeeprofile_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='shift_end',
            field=models.TimeField(blank=True, help_text='Shift End Time', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='shift_start',
            field=models.TimeField(blank=True, help_text='Shift Start Time', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated Commission', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Loyalty Points (1 Haircut = 10 Points)'),
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Silver', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage per service', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='expertise',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in', models.TimeField(auto_now_add=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.employeeprofile')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
