# Generated by Django 6.0 on 2026-02-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=15000.0, help_text='Fixed Monthly Salary', max_digits=10),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month (e.g. 2023-10-01)')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='accounts.employeeprofile')),
            ],
            options={
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
