# Generated by Django 6.0 on 2026-02-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_face_shape_remove_user_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Customer notes or bio'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferences',
            field=models.TextField(blank=True, help_text='Styling preferences (JSON or Text)'),
        ),
    ]
