# Generated by Django 6.0 on 2026-02-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customerprofile_bio_customerprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_first_login_done',
            field=models.BooleanField(default=False, help_text='For Admins to force password reset or OTP on first login'),
        ),
    ]
