# Generated by Django 6.0.1 on 2026-01-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
