# Generated by Django 6.0 on 2026-02-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_time_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_rescheduled',
            field=models.BooleanField(default=False, help_text='Can only reschedule once'),
        ),
    ]
