# Generated by Django 6.0.1 on 2026-02-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_is_rescheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'token_number')},
        ),
    ]
