# Generated by Django 6.0 on 2026-02-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_attendance_date_and_more'),
        ('bookings', '0005_alter_barberqueue_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'token_number'), ('employee', 'booking_date', 'booking_time')},
        ),
    ]
